### ISSUE TITLE
renaming

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#1]
who wants this one
@pcmathias vs @jwrudolf  vs @amromeo

**Comment by jwrudolf** [comment]
I think it may be too advanced for my session. Might fit nicely for Patrick (not to volunteer him).

**Comment by pcmathias** [comment]
I think I agree with Stephan that it'll flow best with the select function as a special case, with reassigning the column name within the select function or using the rename function to keep the original column.

**Comment by amromeo** [comment]
yeah I agree. 
I think of it primarily as a data loading task so at first could make sense in patrick's session. But I think most of us use tidyverse tools to make this happen, which puts it closer to my material.
ill add it somewhere in my session.
