### ISSUE TITLE
Nomenclature for variables/columns/attributes

### ISSUE THREAD

**Issue by hermands** [amromeo/api_r2020#16]
@jwrudolf @amromeo 
Sorry if I missed this earlier.
- 01 is referring to columns as 'attributes', but rstudio writes as 'variables'
- 03 is using 'columns'

I was going to use 'variables'...
What is our convention?

**Comment by pcmathias** [comment]
I think we should follow the R for Data Science terminology and refer to columns as variables and rows as observations.

**Comment by amromeo** [comment]
My personal preference would be column. I think thats what our audience would call them. R/tidyverse isn't really consistent with these things. select() does use variables, but what about
`cbind()`
`bind_cols()`

R4ds says something like: in tidy data Each variable must have its own column, each observation its own row
so to me variable and observation are ideas in the data, a column is that vertical thingee in a data frame.

anyone convinced?

**Comment by pcmathias** [comment]
I think it's fine to use both and agree that column is the physical description of the data structure and variable is an idea. I think we just want to avoid multiple terms for the idea terms.

**Comment by amromeo** [comment]
that works for me as well

**Comment by jwrudolf** [comment]
Sounds good.

I changed my language to variables & columns, rows & observations.
