### ISSUE TITLE
exercises

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#17]
are we putting answers to your turns in the rmd or just the ppt. I've seen this done both ways. if putting in rmd, isn't that right in front of them as they work through the exercise?

could also make separate version of rmd with answers

**Comment by pcmathias** [comment]
I've typically stripped out answers and maintained final copies with answers in a separate place in the repo, then moved those answers over when the course is complete.

**Comment by hermands** [comment]
I've been just putting them in the PPT...but either is fine.

**Comment by amromeo** [comment]
Id do both, we can make a new directory with answer rmds
