### ISSUE TITLE
Peer Review for Amrom

### ISSUE THREAD

**Issue by jwrudolf** [amromeo/api_r2020#19]
@amromeo 

Hi Amrom.

Went through the intro slides and your updated deck.

Intro:
All looks good.  Looks like you left a bit of a gap to be able to pull in some of our presurvey data.  I think that will be cool.  Like the encouragement for folks to introduce themselves to their neighbors too!

Transform deck:
Thanks for the opportunity to share feedback via phone, I like the changes you made and think you are going to be really good for time with ~70 slides.  Really like the way you show pre & post highlighted tables also for the code you execute.

(slide #)

(16) - I'd be prepared to spend some time unpacking the c() function.  This may be one of the first stretches for them (function in a function).
(33) - Appreciate that you broke out the challenge here.  I think beginners will feel more comfortable if they feel like they aren't failing if they don't get through all the components.
(35) - So appreciate that you call out == and =, hugely important for the beginner!
(47) - for exercise 5, the second part may be another opportunity for challenge/extra credit (esp in 3 minutes)
(49) - love the piping slides, might suggest going real slow here, I found piping a bit of a trip when starting R (even after good comfort in python) and since we continue to leverage this throughout, I would hate to lose folks here.
(56) - your turn #6 is a nice synthesis, just a thought to consider some additional skeleton code for them to build off of
(69) - coercing data types may be entering intermediate territory, but since it is at the end of the block, you could definitely gauge abilities and dive deep or pass as you feel the attendees are up for it.  Nice to have in the deck for future reference for sure.

**Comment by amromeo** [comment]
Thanks, these are great suggestions!
appreciate your thoughts re piping, will defineitly take it slow.
i hear you regarding the exercises. 
We are absolutely going to have a substantial skill spectrum in there. Probably the best way to buffer is to have good entry level stuff but allow for people to level up on their own
