### ISSUE TITLE
summary v glimpse v skim

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#2]
@pcmathias were you going to take one of these on?

**Comment by jwrudolf** [comment]
I included summary in the first session.

**Comment by pcmathias** [comment]
I was definitely going to show both summary and glimpse. I can add skim too if the group thinks it's worth throwing it in. Discuss on the call and let me know the verdict.

**Comment by skadauke** [comment]
In general, I would err on the side of introducing fewer commands, and have a didactic reason for introducing each command. I.e., if they don’t absolutely need to understand this idea to achieve one of the objectives of the session, leave it out.

**Comment by amromeo** [comment]
im not a huge skim user, and there are dozens of functions that accomplish what we're describing.

**Comment by pcmathias** [comment]
I ended up only including summary in my content

**Comment by pcmathias** [comment]
Closing out - focus will be on summary.
