### ISSUE TITLE
Peer Review for Stephan

### ISSUE THREAD

**Issue by jwrudolf** [amromeo/api_r2020#20]
@skadauke 

Hi Stephan,

Spent some time with the first half of your slide deck tonight.
(slide #)
(4) love this first visualization, a perfect starter
(8) also really like the time spent on what makes a tidy frame tidy
(7) really like the 1,2,3 of stepping through a ggplot

If you want me to take a deeper spin once you have the full framework up, just let me know.  I can tackle on the airplane tomorrow or give a look Saturday.

**Comment by skadauke** [comment]
Thanks for the feedback! I will upload a revision later today and would love to hear your thoughts.

**Comment by skadauke** [comment]
@jwrudolf if you have any other comments please let me know! Final deck (minus speaker notes) and exercises are on github now.
