### ISSUE TITLE
printing PPTs

### ISSUE THREAD

**Issue by jwrudolf** [amromeo/api_r2020#21]
@amromeo @pcmathias @skadauke @hermands 

Hi all.

Was playing around tonight trying to print slides + notes as PDF.

I can't figure out a way to print multiple slides per page + notes (I can only seem to do one or the other).

I think it would be tough to offer a fully printed course pack at a slide a page.

Guessing I am missing some setting somewhere.

Joe

**Comment by amromeo** [comment]
I think it may be possible to print to pdf a ppt with notes %>%
then open acrobat and print two per page in landscape mode.

investigating

**Comment by skadauke** [comment]
Easiest will be to send slides to me one slide a page. I will print as 2 slides per page, double sided.

**Comment by amromeo** [comment]
you mean, send to you in pdf format correct? because formatting may get messed up on your end?

**Comment by skadauke** [comment]
I think printing notes underneath slides is a bad idea. We don’t want people to read the notes while we’re presenting. If they want the verbatim notes later we can send them after the presentation, and that way they also get the most up to date notes.

**Comment by skadauke** [comment]
Yes exactly

**Comment by amromeo** [comment]
I think notes are helpful if people get lost, day-dream, or if they are referring back during the exercise. but is it worth all the extra paper? @pcmathias @hermands @jwrudolf

**Comment by skadauke** [comment]
Another point – think about whether you’d like to remove some slides from the printed notes. Slides with a figure that builds up one step at a time should be circulated as the fully built figure. Slides with fun cat pics don’t need to be printed. Also, I sometimes like to leave out slides when I ask people to think of the answer to a question (e.g.: what do you think this distribution will look like?) These slides can be put back into the deck for a final version electronically circulated / uploaded to the repo.

**Comment by skadauke** [comment]
Printing course packs now. Closed.
