### ISSUE TITLE
Peer review for Dan

### ISSUE THREAD

**Issue by hermands** [amromeo/api_r2020#22]
I have just uploaded draft of 05 - Stats PPT and Rmd. Sorry it has taken me so long to catch up...

@amromeo I extensively lifted your summarize/group_by material. Thank you! This new version has a lot less "stats", but covers a few basic topics and teaches a lot more manipulation and summarization.

If you happen to have time to review, please share thoughts.

Specific questions:
- Do you teach implicit ungroup differently than slide 25?
- I struggled with variable naming conventions. I think I ended up with the "correct" descriptive, minimal names. For example, `pt_order_count_mean` on slide 25. Thoughts?
- Is Your Turn 5 (slide 30) with group_by(a,b)-summarize-summarize impossible and I should just show? Or is it reasonable to let people struggle with it for a few minutes? 
- Does anyone think we have to show regression? If so, I can add a block to the EDA section.

**Comment by amromeo** [comment]
so 
i think we all are hitting the wall between what people can reasonably learn and what we think is important, at least I am.
I'm thinking about adding a bit of show and tell at the end of my session. 

Like: Everyone close your computer, I'm just going to give you a sense for whats down the line
