### ISSUE TITLE
data import

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#3]
@pcmathias @jwrudolf 

who was going to tackle data import?
will you include pressing "import  dataset" button in upper right pane?
will you include pressing on the file name -> import dataset?

just curious

**Comment by skadauke** [comment]
Do we really want to teach importing data this way?

**Comment by amromeo** [comment]
Not sure which method you're referring to, or both. 
I'd say that these are both useful methods for beginners, certainly can be mentioned. I use the second method all the time, really great way to have GUI write code for me.

**Comment by jwrudolf** [comment]
I am not planning to do any import (just lean on a pre-loaded object).  I think Patrick will address data import.  I could go either way on GUI import or command line (or both).

**Comment by pcmathias** [comment]
I was planning on including in my lesson and showing them read_delim functions and read_excel. I never use the GUI import but can point it out.

**Comment by skadauke** [comment]
I wonder if it’s best practice to teach using GUI tools to autogenerate code. Participants will end up with code that they don’t understand. It sends the message that you don’t really have to understand the code. Import code is easily written by hand and presents an opportunity to cement key ideas about syntax.

**Comment by amromeo** [comment]
I don't think there's necessarily a right or wrong here and I think these are all reasonable options.

I dont think that there's much different between copying and pasting from autogenerated code vs code copied from stackoverflow.

from a learners perspective there is only so much you can learn all at once, and deferring learning the ins and outs of reading in data doesn't seem unreasonable.

**Comment by pcmathias** [comment]
I have included reading csv and Excel commands in my presentation. Will leave it at that and will plan to mention the button in passing.
