### ISSUE TITLE
specific content

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#31]
who is covering 
1. NA
2. warning error message -sk
3. tidy data analysis - pcm
4. what is tidy data - jr et al
5. data types - no one?

**Comment by skadauke** [comment]
I am covering Warning messages in Data Viz. 

From a concept mapping perspective, data import is a great place to introduce both the definition of "Tidy data" (as a special case of "rectangular data") and also the concept of data types.

That said, I have a slide to "review" the Tidy Data definition in Data Viz.

**Comment by skadauke** [comment]
IMHO it is worth hammering home the tidy data idea multiple times
