### ISSUE TITLE
errors and warnings

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#4]
where should we put this topic

**Comment by pcmathias** [comment]
I feel like this one can be dispersed throughout, showing common errors on purpose that we see in practice. The general idea of Googling error messages has some value but I'm not sure how best to tackle this other than showing examples.

**Comment by skadauke** [comment]
I have a whole section on how to deal with errors as a novice in my material in session 2, and I’ve gotten very positive feedback from participants. I would suggest you and Joe look at that and cannibalize most or all of it. :)
