### ISSUE TITLE
4/24/19 Meeting agenda

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#5]
Show progress to date - questions for group
Show EDA dataset - plan moving forward

**Comment by skadauke** [comment]
Deadline for final drafts

Peer review (everyone should look at each other’s slides once and give feedback, with enough lead time so suggestions/corrections can be incorporated)

Printed materials

**Comment by amromeo** [comment]
Minutes:
Push your stuff to github
MIMIC-lite dataset for EDA portion
Deadlines - set
Printed material - Stephan to decide if he can carry material on a plane
