### ISSUE TITLE
Prepopulating Test Catalog

### ISSUE THREAD

**Issue by jwrudolf** [amromeo/api_r2020#6]
@amromeo 

Hi Amrom,

I uploaded the pared data set test_catalog.xlsx to the data folder.

When it is time to prepare the master RStudio Cloud environment, would you mind loading this and assigning to an object called test_catalog?

Thanks!
Joe

**Comment by amromeo** [comment]
hey @jwrudolf im not sure rstudio cloud works the way you imagine. I believe when users log in then they are given a clean environment. no prepopulated objects. could have that wrong though. 
I believe the approved way to do this is to add this to a .Rprofile file, which will get loaded every time that the project is open.
we should confirm that this function is working as planned:
https://github.com/amromeo/api_r2019/commit/1c4638c4f58747888159967f3a8efd255702262a

**Comment by amromeo** [comment]
ok, at least on my first attempt this seemed to work, still needs further confirmation

**Comment by jwrudolf** [comment]
Thanks for investigating Amrom.  Yes, the cloud probably doesn't work the way I imagined (the cloud in general is a mystery to me!)

Maybe we can embed a read xl into the profile (is this what you were testing?)

Other thought is do we need to embed a tidyverse install into the profile or is there another mechanism for staging the workspace for that?

**Comment by pcmathias** [comment]
I signed into the project with a non-admin and saw readxl pre-loaded as well as the test catalog object.  I believe tidyverse is pre-installed by default, I was able to load the package.

**Comment by amromeo** [comment]
i installed tidyverse into the project, so that should be set (could've already been there, not sure). only thing i wasn't sure about was the environment.  thanks patrick for checking it out.
