### ISSUE TITLE
Agenda 5/1

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#7]
@pcmathias @hermands @skadauke @jwrudolf 
On Wednesday we should have peer-reviews of work completed
I'm holding wednesday 2pm as a catch up and for any final issues to discuss
*Please add agenda items below*

- review code/presentation changes/suggestions

**Comment by jwrudolf** [comment]
* discuss how trainees access the cloud instance, reload it if they mess up their workspace, etc.

**Comment by amromeo** [comment]
- do we need two versions of test_catalogue?

**Comment by amromeo** [comment]
- The ppt from stephan and patrick have weird formatting stuff going on:
![image](https://user-images.githubusercontent.com/13033252/57032484-818c9600-6c18-11e9-8fe7-a8dc1d4b2e93.png)
Is this how it looks on your end?

**Comment by pcmathias** [comment]
Discussed on call - probably a Windows vs. Mac ppt issue. Everyone will use their machines to present to class and export presentations to pdf for the repo.

**Comment by pcmathias** [comment]
Also, @amromeo I added the test catalog csv to show importing of a non-Excel file. I am not sure we need the Excel version if it is not used anywhere else (probably requires revising .Rprofile if you remove it, though).
