### ISSUE TITLE
workspace link

### ISSUE THREAD

**Issue by amromeo** [amromeo/api_r2020#8]
@jwrudolf 
saw in your presentation that you were going to go through the process of opening rstudio cloud with the attendees during your sessions, which is a great idea.

the attendees will have to access the workspace with a link, which we can either put directly into your presentation, or we can distribute on paper, as people walk in. 

both are reasonable actions since we will be distributing presentaitons in printed format.

**Comment by jwrudolf** [comment]
Thanks Amrom.

I can easily add the link to the slide deck.  I wasn't sure on how to connect the trainees to cloud instance (do we need to specify their log ins ahead of time to grant them access, can anyone with the link access the instance, if they mess up an object can they easily reload the instance).

Maybe we can spend some time on our next call working out those details.

**Comment by amromeo** [comment]
prior to the workshop I will make the workspace accessible by link and we'll share with attendees, perhaps on your slide deck or also via email.
re: if they mess omething up, they should be able to just rerun the script from start. but lets talk at next meeting
